const products = [
    {
        _id: '1',
        name: 'Airpods Wireless Bluetooth Headphones',
        image: '/images/airpods.jpg',
        description:
            'Bluetooth technology lets you connect it with compatible devices wirelessly. High-quality AAC audio offers an immersive listening experience. Built-in microphone allows you to take calls while working',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id: '2',
        name: 'iPhone 11 Pro 256GB Memory',
        image: '/images/phone.jpg',
        description:
            'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
        brand: 'Apple',
        category: 'Electronics',
        price: 599.99,
        countInStock: 7,
        rating: 4.0,
        numReviews: 8,
    },
    {
        _id: '3',
        name: 'Cannon EOS 80D DSLR Camera',
        image: '/images/camera.jpg',
        description:
            'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
        brand: 'Cannon',
        category: 'Electronics',
        price: 929.99,
        countInStock: 5,
        rating: 3,
        numReviews: 12,
    },
    {
        _id: '4',
        name: 'Sony Playstation 4 Pro White Version',
        image: '/images/playstation.jpg',
        description:
            'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, or music',
        brand: 'Sony',
        category: 'Electronics',
        price: 399.99,
        countInStock: 11,
        rating: 5,
        numReviews: 12,
    },
    {
        _id: '5',
        name: 'Logitech G-Series Gaming Mouse',
        image: '/images/mouse.jpg',
        description:
            'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
        brand: 'Logitech',
        category: 'Electronics',
        price: 49.99,
        countInStock: 7,
        rating: 3.5,
        numReviews: 10,
    },
    {
        _id: '6',
        name: 'Amazon Echo Dot 3rd Generation',
        image: '/images/alexa.jpg',
        description:
            'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small spaces',
        brand: 'Amazon',
        category: 'Electronics',
        price: 29.99,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
    },
    // Additional Items
    {
        _id: '7',
        name: 'Samsung Galaxy S21 Ultra 5G',
        image: '/images/s21ultra.jpg',
        description:
            'Experience the ultimate in smartphone technology with the Samsung Galaxy S21 Ultra 5G. Featuring a stunning display, powerful camera, and 5G capabilities',
        brand: 'Samsung',
        category: 'Electronics',
        price: 1199.99,
        countInStock: 8,
        rating: 4.8,
        numReviews: 20,
    },
    {
        _id: '8',
        name: 'Sony 65-Inch 4K Ultra HD Smart LED TV',
        image: '/images/sonytv.jpg',
        description:
            'Enjoy stunning visuals and immersive entertainment with the Sony 65-Inch 4K Ultra HD Smart LED TV. Featuring advanced picture technologies and a smart interface',
        brand: 'Sony',
        category: 'Electronics',
        price: 1499.99,
        countInStock: 3,
        rating: 4.6,
        numReviews: 15,
    },
    {
        _id: '9',
        name: 'Apple MacBook Pro 13-inch',
        image: '/images/macbook.jpg',
        description:
            'Experience unparalleled performance with the Apple MacBook Pro 13-inch. Packed with powerful hardware and a stunning Retina display, it is perfect for creative professionals',
        brand: 'Apple',
        category: 'Electronics',
        price: 1499.99,
        countInStock: 6,
        rating: 4.7,
        numReviews: 18,
    },
    {
        _id: '10',
        name: 'Samsung 34-Inch Curved WQHD Monitor',
        image: '/images/monitor.jpg',
        description:
            'Immerse yourself in a stunning visual experience with the Samsung 34-Inch Curved WQHD Monitor. Its curved design and high resolution bring content to life',
        brand: 'Samsung',
        category: 'Electronics',
        price: 899.99,
        countInStock: 4,
        rating: 4.4,
        numReviews: 12,
    },
    {
        _id: '11',
        name: 'Bose QuietComfort 35 Wireless Headphones',
        image: '/images/bose.jpg',
        description:
            'Experience exceptional audio quality and noise cancellation with the Bose QuietComfort 35 Wireless Headphones. Perfect for immersive music listening and noise-free calls',
        brand: 'Bose',
        category: 'Electronics',
        price: 299.99,
        countInStock: 9,
        rating: 4.2,
        numReviews: 16,
    },
    {
        _id: '12',
        name: 'Microsoft Surface Pro 7',
        image: '/images/surface.jpg',
        description:
            'Discover the versatility of the Microsoft Surface Pro 7. With its powerful performance, detachable keyboard, and touchscreen display, it adapts to your needs',
        brand: 'Microsoft',
        category: 'Electronics',
        price: 999.99,
        countInStock: 2,
        rating: 4.5,
        numReviews: 14,
    },
    {
        _id: '13',
        name: 'Fitbit Versa 3 Smartwatch',
        image: '/images/fitbit.jpg',
        description:
            'Stay active and track your fitness goals with the Fitbit Versa 3 Smartwatch. It offers advanced health and fitness features, including heart rate monitoring and sleep tracking',
        brand: 'Fitbit',
        category: 'Electronics',
        price: 199.99,
        countInStock: 5,
        rating: 4.3,
        numReviews: 9,
    },
]


export default products; 